### ISSUE TITLE
some troubles

### ISSUE THREAD

**Issue by kang-nj** [BDonnot/ChroniX2Grid#23]
I have run the client to generate chronic with mode "LRTK", "cbc: error: unknown option: -printingOptions" occured and only renewable genertors data in the result file. Is there any solution to resolve this problem?

**Comment by marota** [comment]
"It seems that the cbc module I installed is not which chronix2grid required . Can you share the cbc which chronix2grid required?"
On Mac OSX I have coin-or-tools/coinor/cbc: stable 2.10.3
Check also with pypsa team if that's really the matter because we are just using their package there and they are handling the solvers
